apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: airflow-db
  namespace: soumen-dev
  labels:
    app: airflow
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  paused: false
  selector:
    app: airflow
    deploymentconfig: airflow-db
  template:
    metadata:
      labels:
        name: airflow-db
        app: airflow
        deploymentconfig: airflow-db
    spec:
      volumes:
        - name: airflow-db-data
          persistentVolumeClaim:
            claimName: airflow-db
      containers:
        - name: airflow-db
          image: docker.io/postgres:latest
          resources:
            limits:
              memory: 512Mi
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-db
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-db
                  key: database-password
            - name: POSTGRESQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-db
                  key: database-root-password
            - name: POSTGRESQL_DATABASE 
              valueFrom:
                secretKeyRef:
                  name: airflow-db
                  key: database-name
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: airflow-db-data
              mountPath: /var/lib/postgresql/data
          securityContext:
            capabilities: {}
            privileged: false
          livenessProbe:
            exec:
              command:
              - pg_isready
              - -h
              - localhost
              - -U
              - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - pg_isready
              - -h
              - localhost
              - -U
              - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
