apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: 
  labels:
    app: airflow
spec:
  selector:
    name: airflow-webserver
    app: airflow
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
